### PR TITLE
feature/frame_publisher

### PR DESCRIPTION
**Pull request by lindemeier**
Allowing fixable rotations in transform from one frame to another

### CODE REVIEW

**Review by floweisshardt — APPROVED** [review]
ok for now.

on the long run, we should be able to merge this with the `frame_publisher` node which is used for the `torso_rotated_base_link` (should just be an additional transformation to the base frame).

**Comment by floweisshardt** [comment]
merge together with https://github.com/mojin-robotics/mbl/pull/64

**Comment by floweisshardt** [comment]
@fmessmer feel free to merge

**Review by fmessmer — CHANGES_REQUESTED** [review]
@lindemeier @floweisshardt 
what's the difference between the two nodes?
can we cover both functionalities within a single node - parameterizable via args/yaml?
let's quickly discuss tomorrow...before merging...

**Review by fmessmer — CHANGES_REQUESTED** [review]
as discussed with @lindemeier, I will test the new node in the "old usecase" (i.e. `torso_rotated_base_link`) on a care-o-bot

if it still works there, there is no need in keeping the old implementation (`frame_publisher`) and we can replace the old implementation with the new - but renamed - node provided in this pr

**Comment by fmessmer** [comment]
I'd rather merge #15

**Pull request merged**
