### PR TITLE
set outrange points to max_range -1

### PR DESCRIPTION
**Pull request by floweisshardt**
needed for costmap clearing

### CODE REVIEW

**Comment by mgruhler** [comment]
This is required due to a ["bug"](https://github.com/ros-planning/navigation/issues/124) in `costmap_2d`, where `max_range` and `min_range` is simply not considered...

Also due to the fact that some laser scanners map invalid readings to `max_range`, some to `min_range`...

I guess fine for a workaround here...

**Comment by mgruhler** [comment]
Quickly looking a bit more into it:
- the `ObstacleLayer` transforms all incoming laser scans to a PointCloud ([src](https://github.com/ros-planning/navigation/blob/jade-devel/costmap_2d/plugins/obstacle_layer.cpp#L252-L275))
- the projector throws scans out of the range`[min_range,max_range)` away ([src](https://github.com/ros-perception/laser_geometry/blob/df0be5687241a1e7cd1f757523f5cc80d86da026/include/laser_geometry/laser_geometry.h#L83-L90), [src](https://github.com/ros-perception/laser_geometry/blob/indigo-devel/src/laser_geometry.cpp#L421))

**Comment by mgruhler** [comment]
~~CR: ok~~

Looking at the source code, we should rather define a small `epsilon<range_max` and subtract this. Otherwise, we might introduce strange behaviours, e.g. if `range_max` is just 4.0m, we will end up with some stray 3.0m readings...

**Comment by ipa-svn** [comment]
Use the version in #5 it fixes this as well. I suggest that this PR should be closed without a merge.

**Comment by ipa-svn** [comment]
For every bodies information:
Using ranges < max range instead of =max_range is needed due to that the ranges.assign in sensor_msgs::LaserScan only accepts ranges < max range not <=. 
(It has nothing to do with the costmap apart from that the costmap needs the max range to be part of the scan in order to clear correctly)

**Pull request closed without merging**
